[package]
name = "projectpad-gtk4"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { version = "0.6.6", package = "gtk4", features = ["v4_8"] }
cairo-rs = "0.17.0"
glib = "0.17.9"
gio = "0.17.9"
