[package]
name = "projectpad-gtk4"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { version = "0.7.3", package = "gtk4", features = ["v4_8"] }
cairo-rs = "0.18.2"
glib = "0.18.2"
gio = "0.18.2"
